baseURL: 'https://korya.dev/'
languageCode: 'en-us'
title: '📜 Tech Scrolls'
theme: ["PaperMod"]

menu:
  main:
    - name: Posts
      url: posts/
      weight: 5
    - name: About
      url: about/
      weight: 10

markup:
  highlight:
    codeFences: false # using Highlight.js instead
    noClasses: false
    # style: "solarized-dark"
    # guessSyntax: true
    # pygmentsUseClasses: true
    # pygmentsCodefences: true
    # noClasses: false

params:
  env: production # enable Google Analytics, opengraph, twitter cards and schema
  description: "A personal technical blog by korya: thoughts, reflections and notes"
  # author: "korya"

  defaultTheme: "auto"
  # dateFormat: "2006-01-02"
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  # displayFullLangName: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false # set per post when needed
  comments: true
  images: ["/profile.png"]

  highlight: true

  homeInfoParams:
    enabled: false
    Content: "A personal technical blog by @korya: thoughts, reflections and notes."

  # profileMode:
  #   enabled: false
  #   title: " "
  #   subtitle: "A personal technical blog by korya: thoughts, reflections and notes."
  #   imageUrl: "/profile.png"
  #   imageWidth: 300
  #   imageHeight: 300
  #   buttons:
  #     - name: Posts
  #       url: "/posts"
  #     - name: About
  #       url: "/about"

  # socialIcons:
  #   - name: github
  #     url: 'https://github.com/korya'
  #   - name: twitter
  #     url: 'https://twitter.com/korya_for_real'

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

# Build options
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
publishDir: "build/"

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
